#!/usr/bin/env bash
# ============================================================================
#  Predators & Stealth -- PalSchema aggression patch GENERATOR
#
#  SINGLE SOURCE OF TRUTH for the data patch. Tune a CATEGORY value in the
#  CONFIG block below, run this script, restart Palworld. One number changes
#  every pal in that category -- no hand-editing 300 rows.
#
#      bash tools/gen_aggression.sh
#
#  Emits an aggression jsonc to the live PalSchema mod dir AND a tracked copy
#  in this repo (palschema/aggressive.jsonc).
# ============================================================================
set -uo pipefail

# ===== CONFIG -- tune these, then re-run ====================================
CSV="../PalworldMods/PalClassification.csv"   # pal data (hub, sibling repo)
OUT="/c/Program Files (x86)/Steam/steamapps/common/Palworld/Mods/NativeMods/UE4SS/Mods/PalSchema/mods/PredatorsAndStealth_PoC/raw/aggressive.jsonc"
REPO_COPY="palschema/aggressive.jsonc"        # tracked copy in this repo
NAMES=""                                       # optional "internal,Display" CSV -> adds name comments

HOSTILITY="Warlike"        # AIResponse for every non-prey pal

# HEARD range (HearingRate ~ meters) -- ONE value per hearing category:
HEAR_SHARP=16              # sharp-eared: bats / canines / birds / foxes
HEAR_DEFAULT=10
HEAR_DEAF=6                # deaf / heavy: golems / turtles / rock / metal

# AGGRO range (ViewingDistance, meters) by Hp tier:
VD_BASE=25
VD_MID=32  ; VD_MID_HP=100
VD_HIGH=40 ; VD_HIGH_HP=140

# category membership (regex on internal row name):
SHARP_RE="Bat|Rabbit|Bunny|Fox|Dog|Wolf|Cat|Bird|Owl|Hawk|Eagle|Crow|Deer|Lynx|Ferret|Jackal"
DEAF_RE="Golem|Turtle|Tortoise|Rock|Stone|Crab|Mammoth|Metal|Mecha|Fortress"

# prey stay passive (excluded from the patch):
PREY="chickenpal sheepball mimicdog dreamdemon carbunclo pinkcat cutefox woolfox cowpal alpaca penguin"
# ===========================================================================

cd "$(dirname "$0")/.."          # repo root
mkdir -p "$(dirname "$REPO_COPY")"

awk -F, \
  -v prey_s="$PREY" -v host="$HOSTILITY" \
  -v hs="$HEAR_SHARP" -v hd="$HEAR_DEFAULT" -v hf="$HEAR_DEAF" \
  -v vb="$VD_BASE" -v vm="$VD_MID" -v vmhp="$VD_MID_HP" -v vh="$VD_HIGH" -v vhhp="$VD_HIGH_HP" \
  -v sharp_re="$SHARP_RE" -v deaf_re="$DEAF_RE" -v namesfile="$NAMES" '
BEGIN{
  split(prey_s, a, " "); for(i in a) prey[a[i]]=1
  split("Escape Escape_to_Battle NotInterested Friendly Warlike", k, " "); for(i in k) keep[k[i]]=1
  if (namesfile!="") while ((getline ln < namesfile) > 0) { split(ln, nn, ","); n2d[nn[1]]=nn[2] }
}
NR==1{next}
{
  gsub(/\r/,"")
  pal=$1; resp=$5; hp=$13+0
  if($14=="true"||$15=="true"||$16=="true") next          # skip bosses/tower/raid
  if(tolower(pal) in prey) next                            # skip prey
  if(pal ~ /^POLICE_/) next                                # skip guard pals
  if(!(resp in keep)) next                                 # skip quest oddballs
  vd=vb; if(hp>=vhhp) vd=vh; else if(hp>=vmhp) vd=vm
  hr=hd; hc="default"
  if(pal ~ sharp_re){ hr=hs; hc="sharp" } else if(pal ~ deaf_re){ hr=hf; hc="deaf" }
  n++; P[n]=pal; VD[n]=vd; HR[n]=hr; HC[n]=hc
}
END{
  print "// Predators \x26 Stealth -- PalSchema aggression patch (GENERATED by tools/gen_aggression.sh)."
  print "// Change CATEGORY values in the generator CONFIG and re-run -- do not hand-edit here."
  print "// Knobs: AIResponse (hostility) | ViewingDistance (aggro/sight m) | HearingRate (heard m)."
  print "// AIResponse tags: Warlike | Escape_to_Battle | NotInterested | Escape | Friendly | (Kill_All/Boss avoid)."
  print "{"
  print "  \"DT_PalMonsterParameter\": {"
  for(i=1;i<=n;i++){
    sep=(i<n)?",":""
    dn=(namesfile!="" && (P[i] in n2d))?n2d[P[i]]:""
    cmt="// " (dn!=""? dn "  ":"") "[" HC[i] " hear, VD" VD[i] "]"
    printf "    \"%s\": { \"AIResponse\": \"%s\", \"ViewingDistance\": %d, \"HearingRate\": %d.0 }%s %s\n", P[i], host, VD[i], HR[i], sep, cmt
  }
  print "  }"
  print "}"
}
' "$CSV" | tee "$OUT" > "$REPO_COPY"

echo "generated $(grep -c '\"AIResponse\"' "$REPO_COPY") entries"
echo "  -> live:  $OUT"
echo "  -> repo:  $REPO_COPY"
